-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente integer NOT NULL DEFAULT nextval('cliente_id_cliente_seq'::regclass),
    nome_cliente character varying(100) COLLATE pg_catalog."default" NOT NULL,
    endereco character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.loja
(
    id_loja integer NOT NULL DEFAULT nextval('loja_id_loja_seq'::regclass),
    cod_loja integer NOT NULL,
    nome_loja character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT loja_pkey PRIMARY KEY (id_loja)
);

CREATE TABLE IF NOT EXISTS public.produto
(
    id_produto integer NOT NULL DEFAULT nextval('produto_id_produto_seq'::regclass),
    cod_produto integer NOT NULL,
    nome_produto character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT produto_pkey PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS public.vendas
(
    id_loja integer NOT NULL DEFAULT nextval('vendas_id_loja_seq'::regclass),
    id_produto integer NOT NULL DEFAULT nextval('vendas_id_produto_seq'::regclass),
    id_cliente integer NOT NULL DEFAULT nextval('vendas_id_cliente_seq'::regclass),
    valor money NOT NULL
);

ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT id_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT id_loja FOREIGN KEY (id_loja)
    REFERENCES public.loja (id_loja) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT id_produto FOREIGN KEY (id_produto)
    REFERENCES public.produto (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

SELECT * FROM cliente;
SELECT * FROM produto;
SELECT * FROM loja;
SELECT * FROM vendas;

INSERT INTO cliente (nome_cliente, endereco) VALUES('José Bonifácio','R. Pedro Alvares Cabral');
INSERT INTO loja (cod_loja, nome_loja) VALUES('001','Armazém Esperança');


